---
title: "Expository graphics"
author: "Rabya Ghafoor"
date: "4/21/2020"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

1.
```{r}
download.file(url="https://ndownloader.figshare.com/files/2292169",
              destfile = "data/portal_data_joined.csv")
```

```{r}
surveys <- read.csv("data/portal_data_joined.csv")
surveys_complete <- surveys %>%
  filter(!is.na(weight),           # remove missing weight
         !is.na(hindfoot_length),  # remove missing hindfoot_length
         !is.na(sex))                # remove missing sex


## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)

write_csv(surveys_complete, path = "data/surveys_complete.csv")
```

```{r}
surveys_complete <- read_csv("data/surveys_complete.csv")
```

```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
  labs(title = "Hindfoot length vs Weight by Species ID",
      subtitle = "Hindfoot length generally increases with weight with the exception of Neotoma",
     y = "Hindfoot length (cm)",
    x = "Weight (kg)"
 )
```

2. 
```{r}
best_in_genus <- surveys_complete%>%
  group_by(genus) %>%
  filter(row_number(desc(hindfoot_length)) == 1)
## Warning in rep.default(list_of(integer()), length = nrow(groups)): partial
## argument match of 'length' to 'length.out'
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(colour = genus)) +
  geom_text(aes(label = species), data = best_in_genus)
```
```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(colour = genus)) +
  geom_point(size = 3, shape = 1, data = best_in_genus) +
  ggrepel::geom_label_repel(aes(label = species), data = best_in_genus)
```

3. 
```{r}
text_df <- tibble(text = "test\nthis\nout", x = 300, y = 60)
g1 <- ggplot(surveys_complete, aes(weight, hindfoot_length)) +
   geom_point()
g1 + geom_text(aes(x, y, label = text), data = text_df)

```

```{r}
label <- surveys_complete %>%
  summarise(
    hindfoot_length = max(hindfoot_length),
    weight = max(weight),
    hindfoot_length_min = min(hindfoot_length),
    weight_min = min(weight),
    label = "Increasing weight generally related to increasing hindfoot length."
  )

g1 + geom_text(aes(label = label), data = label, 
            vjust = "top", hjust = "right") 


```
  
  
```{r}
fit <- lm(hindfoot_length ~ weight, data = surveys_complete)
surveys_complete$predicted <- predict(fit)
surveys_complete$residuals < residuals(fit)

```
```{r}
ggplot(surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_segment(aes(xend = weight, yend = predicted)) +
  geom_point() +
  geom_point(aes(y = predicted), shape = 1)
```

4. 
```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(colour = genus))+
  scale_y_continuous(breaks = seq(0, 60, by = 6))
```

5.

```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  scale_colour_brewer(palette = "Set1")
```

```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  scale_colour_brewer(palette = "Set3")
```


6.
```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
  theme_dark()
```


```{r}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
  theme_minimal() 
```

7. 
```{r fig.width = 4}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
    labs(caption = "fig.width = 4")
```


```{r fig.width = 8}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
    labs(caption = "fig.width = 8")
```


```{r fig.width = 10}
ggplot(surveys_complete, aes(weight, hindfoot_length)) +
  geom_point(aes(color = genus)) +
  geom_smooth(se = FALSE) +
    labs(caption = "fig.width = 10") +
  ggsave("plot_weight_hindfoot.jpeg")
```